// Поля для light-карточек по типу
export const lightCardFields = {
    excursions: {
        slug: 1,
        type: 1,
        "translation.title": 1,
        "translation.shortDescription": 1,
        "translation.city": 1,
        price: 1,
        duration: 1,
        images: { $slice: ["$images", 1] },
        rating: 1,
        reviewsCount: 1,
        active: 1,
    },
    yachts: {
        slug: 1,
        type: 1,
        "translation.title": 1,
        "translation.shortDescription": 1,
        price: 1,
        capacity: 1,
        images: { $slice: ["$images", 1] },
        rating: 1,
        reviewsCount: 1,
        active: 1,
    },
    blogs: {
        slug: 1,
        type: 1,
        "translation.title": 1,
        "translation.excerpt": 1,
        "translation.metaDescription": 1,
        publishDate: 1,
        author: 1,
        images: { $slice: ["$images", 1] },
        active: 1,
    },
    places: {
        slug: 1,
        type: 1,
        "translation.title": 1,
        "translation.city": 1,
        "translation.shortDescription": 1,
        images: { $slice: ["$images", 1] },
        rating: 1,
        reviewsCount: 1,
        active: 1,
    },
};
